version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=80'
    image: 'snojo/tictactoe:${GIT_COMMIT}'
    ports:
      - '80:80'
    links:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=postgres'
    expose:
      - '5432'
